# Pull in python for access to pip for hererocks
language: python

sudo: false

addons:
    apt:
        packages:
            - libevent-dev

env:
    global:
        - LUAROCKS=3.3
    matrix:
        - LUA="moonjit 2.1"
        - LUA="luajit 2.1"
        - LUA="luajit 2.0"
        - LUA="lua 5.4"
        - LUA="lua 5.3"
        - LUA="lua 5.2"
        - LUA="lua 5.1"

before_install:
    - pip install hererocks
    - hererocks env -r $LUAROCKS --$LUA
    - source env/bin/activate
    - luarocks install busted

script:
    - luarocks make rockspecs/luaevent/luaevent-scm-1.rockspec
    - cd test && busted event_buffer-tests.lua

notifications:
    email:
        on_success: change
        on_failure: always
